### ISSUE TITLE
djangojs does not handle unimported installed_apps, throws error.

### ISSUE THREAD

**Issue by simondrabble** [noirbizarre/django.js#31]
When the djangojs.urls file is processed, any apps in INSTALLED_APPS that are not explicitly imported cause processing to fail. Traceback below. A work-around is to ensure that any such apps are imported e.g. in settings.py:

```
import widget_tweaks
```

A better fix would be to ensure these apps are imported directly in djangojs.urls.

Traceback:

```
mod_wsgi (pid=4728): Exception occurred processing WSGI script '/home/rumple/webapps/project/project/project/wsgi.py'.
Traceback (most recent call last):
  File "/home/rumple/webapps/project/lib/python2.7/django/core/handlers/wsgi.py", line 241, in __call__
    response = self.get_response(request)
  File "/home/rumple/webapps/project/lib/python2.7/django/core/handlers/base.py", line 179, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/home/rumple/webapps/project/lib/python2.7/django/core/handlers/base.py", line 224, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/home/rumple/webapps/project/lib/python2.7/django/core/urlresolvers.py", line 323, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/rumple/webapps/project/lib/python2.7/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/rumple/webapps/project/project/project/urls.py", line 12, in <module>
    url(r'^djangojs/', include('djangojs.urls')),
  File "/home/rumple/webapps/project/lib/python2.7/django/conf/urls/__init__.py", line 24, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/rumple/webapps/project/lib/python2.7/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/rumple/lib/python2.7/djangojs/urls.py", line 35, in <module>
    url(r'^translation$', 'django.views.i18n.javascript_catalog', js_info_dict(), name='js_catalog'),
  File "/home/rumple/lib/python2.7/djangojs/urls.py", line 23, in js_info_dict
    module = sys.modules[app]
KeyError: 'widget_tweaks'
```

**Comment by noirbizarre** [comment]
Thanks for the report.
I will try to fix a proper fix.
There maybe some side effects of importing apps, I need to test before.

By the way, on which Django version did it happen ? 1.6 ?

**Comment by simondrabble** [comment]
1.4

**Comment by simondrabble** [comment]
Any movement on this? I recently added celery to my INSTALLED_APPS and django.js requires it be imported in settings, unfortunately doing so causes other issues.

**Comment by noirbizarre** [comment]
Sorry, I didn't had time.

I will try to look at it this week-end.

If you already have a solution, don't hesitate to submit a PR.

**Comment by tazor** [comment]
Any news on this? It's a real showstopper for an otherwise excellent library!

**Comment by noirbizarre** [comment]
Sorry, 

I've been overbooked until now. 
I will fix that in the coming weeks, I promise!
