### ISSUE TITLE
Issue with automatic installation

### ISSUE THREAD

**Issue by drummonds** [noirbizarre/django.js#37]
When I install django.js on a Ubuntu 14.04 machine in Python 3.4 virtual environment I get the following error message below.  My work around is to manually install it which works and the automatic installation which uses ansible recognises that it is installed and all is ok.

```
Downloading/unpacking django.js==0.8.1 (from -r /home/ubuntu/projects/galleria/requirements/base.txt (line 15))
  Running setup.py (path:/home/ubuntu/.virtualenvs/galleria/build/django.js/setup.py) egg_info for package django.js
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/ubuntu/.virtualenvs/galleria/build/django.js/setup.py", line 36, in <module>
        rst('CHANGELOG.rst'),
      File "/home/ubuntu/.virtualenvs/galleria/build/django.js/setup.py", line 28, in rst
        content = open(filename).read()
      File "/home/ubuntu/.virtualenvs/galleria/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1543: ordinal not in range(128)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/ubuntu/.virtualenvs/galleria/build/django.js/setup.py", line 36, in <module>

    rst('CHANGELOG.rst'),
```

**Comment by noirbizarre** [comment]
I believe it's the same issue than #40 and so it should be fixed by 33620f1565
